### ISSUE TITLE
Data Client Contracts MVP

### ISSUE THREAD

**Issue by scotthconner** [FilOzone/starmap#2]
eta: 2022-12-31

description:
Enable smart contracts to make deals with Filecoin storage providers automatically. This milestone is measured as complete with a demonstration of Filecoin Deal Client Contracts and DataDaos.

- Smart contracts as deal clients
- make storage deals with Filecoin SP with client contracts
- enable deal persistence service

You can read more on Notion: https://www.notion.so/Data-Client-Contracts-MVP-fddba2b6c41749c9b284f5cc7cbd40a1

**Comment by momack2** [comment]
This is now shipped on mainnet!!
(can we mark as closed?)

**Comment by scotthconner** [comment]
Boom!

**Comment by quickhatche** [comment]
@scotthconner Looks like this is still opened; Can you check in here and close so we can have the EngRes starmap updated before tomorrow?
